# Generated by Django 5.1.1 on 2024-09-24 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_structure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectentity',
            name='django_element_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='projectentity',
            name='file_extension',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='projectentity',
            name='file_size_category',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
