# Generated by Django 5.1 on 2024-08-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=255)),
                ('job_location', models.CharField(max_length=255)),
                ('date_of_application', models.DateField()),
                ('time_of_application', models.TimeField()),
                ('designation', models.CharField(max_length=255)),
            ],
        ),
    ]
