# Generated by Django 5.1 on 2024-08-26 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='job_location',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='time_of_application',
        ),
    ]
