# Generated by Django 5.1 on 2024-08-26 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_job_location_jobapplication_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='location',
            new_name='time_of_application',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='job_location',
            field=models.TextField(default='Unknown'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='designation',
            field=models.TextField(),
        ),
    ]
