# Generated by Django 5.1 on 2024-08-26 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_location_jobapplication_time_of_application_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='designation',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='job_location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterModelTable(
            name='jobapplication',
            table='applications',
        ),
    ]
