# Generated by Django 5.1.1 on 2024-09-30 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directory', models.CharField(max_length=500)),
                ('filename', models.CharField(max_length=255)),
                ('full_path', models.CharField(max_length=1000)),
                ('file_size', models.BigIntegerField()),
                ('metadata_change_time', models.DateTimeField()),
                ('modification_time', models.DateTimeField()),
                ('access_time', models.DateTimeField()),
                ('file_age_in_days', models.IntegerField()),
                ('meta_data_age_in_days', models.IntegerField()),
                ('recently_accessed', models.BooleanField(default=False)),
                ('file_size_category', models.CharField(blank=True, max_length=500, null=True)),
                ('file_extension', models.CharField(blank=True, max_length=100, null=True)),
                ('python_file', models.BooleanField(default=False)),
                ('file_depth', models.IntegerField()),
                ('django_element_type', models.CharField(blank=True, max_length=100, null=True)),
                ('expected_location', models.BooleanField(default=False)),
                ('hover_template', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
